### ISSUE TITLE
Implicit string joining in the function signature

### ISSUE THREAD

**Issue by vaultah** [MattDMo/PythonImproved#32] opened 2015-03-01 13:23 UTC
PI does not properly handle/highlight the`'second part'` in the function signature, although Python allows string concatenation via [implicit line joining](https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining):

![doesnot](https://cloud.githubusercontent.com/assets/4944562/6430851/0da509f2-c014-11e4-9dc2-f1d9eb7397ba.png)

OTOH, function calls are handled well:

![works](https://cloud.githubusercontent.com/assets/4944562/6431230/cc85c2d8-c020-11e4-98c1-4ce1b85e4d6b.png)

**Comment by MattDMo** [comment] 2015-03-02 20:37
Thanks, I'll look into it.

**Comment by MattDMo** [comment] 2015-09-10 05:19
The reason for this is complicated, and I still don't know how to fix it. Basically, dunder methods like `__init__`, `__add__`, etc. are not treated *quite* like normal functions in PI, and I can't yet figure out what scoping I need to mess with in order to fix that. Also, your second example isn't quite equivalent to the first, as the first split string is in the arguments of a function *definition*, while the second split string is in the arguments of a function *call*.

**Comment by MattDMo** [comment] 2015-11-01 07:01
I just noticed this again. @FichteFoll, any thoughts?

**Comment by FichteFoll** [comment] 2015-11-01 15:42
I didn't take a look at function definitions when I worked on PyI. Anyway, the problem is [here](https://github.com/MattDMo/PythonImproved/blob/b5f5a211769f0061059db4018b5e9171d264be41/PythonImproved.YAML-tmLanguage#L760), where a newline terminates further parsing of keyword argument default values, although it should only be terminated by `,` or `)`.

**Comment by MattDMo** [comment] 2015-11-02 03:01
Same issue as [SublimeTextIssues/DefaultPackages #158](https://github.com/SublimeTextIssues/DefaultPackages/issues/158).

**Comment by MattDMo** [comment] 2015-12-04 15:18
This has been fixed in the 2.0 release:

<img width="325" alt="implicit string joining in function definition" src="https://cloud.githubusercontent.com/assets/1776358/11593065/385b610a-9a70-11e5-8943-dae9a5865a9a.png">

**Closed by MattDMo** 2015-12-04 15:18 UTC
Labels: bug
