### ISSUE TITLE
Syntax highlighting error when [ inside of r"""string""".

### ISSUE THREAD

**Issue by MartinThoma** [MattDMo/PythonImproved#59] opened 2016-02-08 07:42 UTC
Minimal example:

```python
r""" This is["""
seriously = '?'
```

**Comment by MattDMo** [comment] 2016-02-08 17:27
Duplicate of #34

**Closed by MattDMo** 2016-02-08 17:27 UTC
Labels: duplicate

**Comment by MartinThoma** [comment] 2016-02-08 21:58
See also: https://github.com/SublimeTextIssues/DefaultPackages/issues/173
