### ISSUE TITLE
Expressions breaking the syntax parsing

### ISSUE THREAD

**Issue by Loamhoof** [MattDMo/PythonImproved#27] opened 2015-02-04 10:21 UTC
Been having issues regarding the syntax parsing since the last update: some expressions seem to break the syntax highlighting, like raising an exception `raise Exception(some_message)` or a tuple of exceptions in an except `except (FirstException, SecondException):`.

Example of what it looks like after those lines:
![image](https://cloud.githubusercontent.com/assets/2034418/6038717/d1d66f28-ac5f-11e4-8ea9-175bcde768c9.png)

**Comment by DoctorMalboro** [comment] 2015-02-04 12:21
I can confirm this issue too
![Broken code](https://cloud.githubusercontent.com/assets/553651/6040314/0fef3b8e-ac4f-11e4-9939-3c6e3012397e.png)

**Comment by DanielOaks** [comment] 2015-02-04 13:30
Can confirm this issue here too

![screen shot 2015-02-04 at 11 28 52 pm](https://cloud.githubusercontent.com/assets/251281/6041193/c30acbea-acc5-11e4-96eb-24a2f545a0bb.png)

**Comment by MattDMo** [comment] 2015-02-04 16:13
Thanks for the feedback, everyone. For now I'm going to roll back to the previous version until I can figure out what went wrong.

**Comment by MattDMo** [comment] 2015-02-04 16:40
OK, I figured out what the problem was - I was experimenting with some tuple highlighting, and somehow those rules completely overrode the function arguments ones. This is what happens when you release at 1 AM and don't test enough :grimacing: 
[Release 1.4.1](https://github.com/MattDMo/PythonImproved/releases/tag/1.4.1) fixes this.

**Comment by DanielOaks** [comment] 2015-02-04 16:57
Fair enough. Thanks for the quick fix, PythonImproved is damn useful!

**Comment by vaultah** [comment] 2015-02-04 17:08
Re-installing fixed the above issues, but now I see the other possible problem:

![](http://i.imgur.com/AZjHzv0.png)

**Comment by Loamhoof** [comment] 2015-02-04 17:12
Glad I can use it again, thanks! :)

**Comment by MattDMo** [comment] 2015-02-04 18:08
OK, so there was another regression that has been fixed in 1.4.2, which I just released. Major PITA...

**Comment by 20115681** [comment] 2015-02-05 06:33
[DoctorMalboro] (https://github.com/DoctorMalboro)
What font do you use in above screenshot?

**Closed** 2015-02-05 21:14 UTC
Labels: bug
